version: '3.8'

services:

  iics-docker-agent:
    container_name: iics-docker-agent
    hostname: iics-docker-agent
    image: local/iics-secure-agent:latest
    restart: always
    environment:
      IICS_RUNTIME_NAME: "${IICS_RUNTIME_NAME}"
      IICS_TENANT_NAME: "${IICS_TENANT_NAME}"
      IICS_TOKEN: "${IICS_TOKEN}"
    volumes:
      - iics-agent-volume:/home/iics-agent
      - "./flatfiles:/flatfiles"

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - 1433:1433
    volumes:
      - "./backups:/var/backups"
      - sql-server-volume2:/var/opt/mssql

  mysql:
    image: mysql:latest
    hostname: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: iics
      MYSQL_USER: iics
      MYSQL_PASSWORD: iics
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  iics-agent-volume:
  sql-server-volume:
  mysql-volume:


