version: '3.8'

services:

  iics-secure-agent:
    container_name: iics-secure-docker-agent
    hostname: iics-secure-docker-agent
    image: local/iics-secure-agent:latest
    restart: always
    environment:
      IICS_RUNTIME_NAME: "${IICS_RUNTIME_NAME}"
      IICS_TENANT_NAME: "${IICS_TENANT_NAME}"
      IICS_TOKEN: "${IICS_TOKEN}"
    volumes:
      - "./flatfiles:/flatfiles"

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - 1433:1433
    volumes:
      - sql-server-volume:/var/opt/mssql

  mysql:
    image: mysql:latest
    hostname: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: iics
      MYSQL_USER: iics
      MYSQL_PASSWORD: iics
    volumes:
      - "./mysql/custom-config.cnf:/etc/mysql/conf.d/custom-config.cnf"

volumes:
  sql-server-volume:


